### ISSUE TITLE
md5 return other hash key with one string

### ISSUE THREAD

**Issue by sinhpn92** [5peak2me/jni-md5#1]
I have hash just 1 string in two device and this function return two hash string. what's wrong here?
i use device Galaxy J and galaxy s7.
App on device Galaxy s7 return wrong hashstring.

**Comment by 5peak2me** [comment]
@sinhpn92 pls upload the code and screenshot

**Comment by RaymondZY** [comment]
I have the same problem.
After a few hours digging, I finally found the size of "unsinged long" is various in different platform.
It's not always 4 bytes long as expected. It's 8 bytes long in one 64-bits machine.
Changing "typedef unsigned long UINT4" into "typedef unsigned int UINT4" in file md5.h will fix the error.
